// @ts-nocheck
import * as __fd_glob_51 from "../content/docs/providers/replicate.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/providers/index.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/providers/hume.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/providers/fal.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/providers/elevenlabs.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/models/whisper.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/models/seedream.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/models/seedance.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/models/nano-banana.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/models/nano-banana-pro.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/models/minimax.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/models/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/models/hume.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/models/fast-whisper.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/models/fabric.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/models/elevenlabs.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/models/background-remover.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/operations/merge.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/operations/layers.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/operations/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/operations/captions.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/core-concepts/providers.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/core-concepts/pipelines.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/core-concepts/models.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/core-concepts/index.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/integrations/index.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/integrations/cdn.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/generation/video.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/generation/index.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/generation/image.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/generation/audio.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/guides/webhooks.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/guides/multi-scene-videos.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/guides/error-handling.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/guides/ai-agents.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api-reference/types.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api-reference/index.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/api-reference/execution.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/api-reference/execute-from-plan.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/api-reference/compose.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/quickstart.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/providers/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/operations/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/models/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/integrations/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/generation/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/core-concepts/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/api-reference/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "api-reference/meta.json": __fd_glob_1, "guides/meta.json": __fd_glob_2, "core-concepts/meta.json": __fd_glob_3, "generation/meta.json": __fd_glob_4, "integrations/meta.json": __fd_glob_5, "models/meta.json": __fd_glob_6, "operations/meta.json": __fd_glob_7, "providers/meta.json": __fd_glob_8, }, {"index.mdx": __fd_glob_9, "quickstart.mdx": __fd_glob_10, "api-reference/compose.mdx": __fd_glob_11, "api-reference/execute-from-plan.mdx": __fd_glob_12, "api-reference/execution.mdx": __fd_glob_13, "api-reference/index.mdx": __fd_glob_14, "api-reference/types.mdx": __fd_glob_15, "guides/ai-agents.mdx": __fd_glob_16, "guides/error-handling.mdx": __fd_glob_17, "guides/index.mdx": __fd_glob_18, "guides/multi-scene-videos.mdx": __fd_glob_19, "guides/webhooks.mdx": __fd_glob_20, "generation/audio.mdx": __fd_glob_21, "generation/image.mdx": __fd_glob_22, "generation/index.mdx": __fd_glob_23, "generation/video.mdx": __fd_glob_24, "integrations/cdn.mdx": __fd_glob_25, "integrations/index.mdx": __fd_glob_26, "core-concepts/index.mdx": __fd_glob_27, "core-concepts/models.mdx": __fd_glob_28, "core-concepts/pipelines.mdx": __fd_glob_29, "core-concepts/providers.mdx": __fd_glob_30, "operations/captions.mdx": __fd_glob_31, "operations/index.mdx": __fd_glob_32, "operations/layers.mdx": __fd_glob_33, "operations/merge.mdx": __fd_glob_34, "models/background-remover.mdx": __fd_glob_35, "models/elevenlabs.mdx": __fd_glob_36, "models/fabric.mdx": __fd_glob_37, "models/fast-whisper.mdx": __fd_glob_38, "models/hume.mdx": __fd_glob_39, "models/index.mdx": __fd_glob_40, "models/minimax.mdx": __fd_glob_41, "models/nano-banana-pro.mdx": __fd_glob_42, "models/nano-banana.mdx": __fd_glob_43, "models/seedance.mdx": __fd_glob_44, "models/seedream.mdx": __fd_glob_45, "models/whisper.mdx": __fd_glob_46, "providers/elevenlabs.mdx": __fd_glob_47, "providers/fal.mdx": __fd_glob_48, "providers/hume.mdx": __fd_glob_49, "providers/index.mdx": __fd_glob_50, "providers/replicate.mdx": __fd_glob_51, });