import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tailark Quartz pages",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <Header /> */}
      <main role="main" data-theme="dark" className="bg-background">
        {children}
      </main>
      {/* <FooterSection /> */}
    </>
  );
}
